name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --verbose
    - name: Tests
      run: cargo test -r --verbose


  test-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
    - run: vcpkg install openssl:x64-windows-static-md
    - name: Build
      run: cargo build -r --verbose
    - name: Test
      run: cargo test -r --verbose
