name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --verbose
    - name: Run tests
      run: cargo test -r --verbose


  build_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install OpenSSL
      run: winget install --id ShiningLight.OpenSSL && setx PATH "%PATH%;C:\Program Files\OpenSSL-Win64\bin" /M
    - name: Build
      run: cargo build -r --verbose
    - name: Run tests
      run: cargo test -r --verbose
